apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: modresorts
    app.kubernetes.io/instance: websphere
    app.kubernetes.io/name: modresorts
    release: websphere
  name: modresorts
  namespace: NAMESPACE
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: https
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app: modresorts
  sessionAffinity: None
  type: ClusterIP
